apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: udagram-api
  name: udagram-api
spec:
  ports:
  - name: api-port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-api
  type: LoadBalancer
status:
  loadBalancer: {}
